// Generated by CoffeeScript 1.8.0
(function() {
  this.HtmlParser = function() {
    this.filters = [];
  };

  this.HtmlParser.prototype.add_filter = function(filter) {
    this.filters.push(filter);
  };

  this.HtmlParser.prototype.parse = function(text) {
    var index;
    for (index in this.filters) {
      text = this.filters[index].apply(text);
    }
    return text;
  };

}).call(this);
